name: CI for Swift Console Application

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
    - name: Check out the repository
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build the application
      run: swift build --build-tests
    
    - name: Run tests
      run: swift test
